== Prompts to sort

* <https://s.mj.run/vlYVuPDTPek> <https://s.mj.run/WUN1v6dIXiM> a stunning woman, holding a book on fire to her chest, her hair is embellished with shimmering gold chains and delicate ornaments, hyper detailed, cinematic lighting, Kodak Vision3 500T film stock, 35 mm shot, diminished minimalism background, 8K resolution
* a sunlight comes through the forest with some trees, in the style of anime art, lush and detailed, storybook-like, anime-inspired, i can't believe how beautiful this is
* Doctor Strange taking a selfie with a GoPro on top of a building on Chinese palace , fish eye lens, high detail, ultra realistic, cinematic lighting, portrait painting, photorealistic, Color Grading, portrait Photography, hyper - detailed, beautifully color graded, Unreal Engine5, Cinematic 8K
* A surreal image of a giant jellyfish floating in the sky with its tentacles trailing down to the ground and wrapping around a city skyline.
* young female Obi Wan Kenobi, dynamic pose, in the style of Star Wars, yanjun cheng, krenz cushart, Frank Frazetta, ultra detailed illustration, tristan eaton, becky cloonan, serge marshennikov, spare and elegant brushwork, bone, eye-catching
* Wonder woman posing, portraiture, intense close - ups, Lois Van Baarle, by Krenz Cushart, Syd Mead, in the style of gold blue and red blink - and - you - miss - it detail, mirrored realms, suspended/ hanging, romanticized femininity
* Impasto oil watercolor and alcohol painting :: graceful beautiful gorgeous woman ballerina, Pino Daeni :: 3d arctic blue smoke and glacial blue swirling fog on white background :: romantic impressionism :: white background ::
* concept artist, Paul Chadeisson, futuristic cityscape, towering skyscrapers, advanced technology, bustling population, humans, robots, digital painting techniques, character, architecture, infrastructure, intricate details.
* Modern surreal extreme close up, Macro photo of pin up in heaven, beautiful eyes, dynamic pose, tilt angle by boris vallejo,Norman Rockwell, Milo manara, artgerm, mcbess UHD, 8k super Sharp Focus
* moon art, in the style of dreamlike illustrations, dark aquamarine and gold, colorful costumes, dreamy atmosphere, dark aquamarine and orange, celebrity portraits, dream-like atmosphere
* a woman’s head surrounded by multiple ovals and circles, in the style of richly detailed art nouveau, artgerm, sky-blue and amber, detailed world-building, orange and black, contrasting shadows, concert poster, alexandr averin

== Ideas

* Kids Coloring Book
* Twitter Campaign on Patriotic Cyber/IT Pics

== User Guide

* https://docs.midjourney.com/docs/quick-start

== General Prompt Links

* https://twitter.com/javilopen/status/1642934866726768641?s=66&t=U90L9708TveKgva-sK5qYw
* https://www.creativindie.com/best-midjourney-prompts-an-epic-list-of-crazy-text-to-image-ideas/#:~:text=Best%20MidJourney%20Prompts%3A%20camera%20lenses%20and%20filters&text=%E2%80%9CExpansive%20landscapes%2C%E2%80%9D%20%E2%80%9CSweeping,Including%20more%20of%20the%20scene.%E2%80%9D
* https://wgmimedia.com/how-to-make-a-logo-with-midjourney/
* https://www.ebaqdesign.com/blog/midjourney-logo-design
* https://www.midjourney.com/account/
* https://twitter.com/jhaddix/status/1645515555258990601?s=66&t=U90L9708TveKgva-sK5qYw
** IMAGE_TYPE: X | GENRE: X | EMOTION: X| SCENE: X | ACTORS: X | LOCATION TYPE: X | CAMERA MODEL: X | CAMERA LENSE: X | SPECIAL EFFECTS: X | TAGS: X, X, X, X, X — ar 16:9
* https://medium.com/@neonforge/chatgpt-midjourney-dall-e-and-stable-diffusion-how-to-create-amazing-images-for-almost-any-5daced80f376

== Signup

====
Midjourney Bot
 — Today at 9:26 AM
Heya @chrismh, we're excited to have you as part of the Midjourney Beta!

Other important tips
- For visual guides and docs  https://docs.midjourney.com/docs/quick-start
- When your trial ends type /subscribe or go to https://midjourney.com/account
- To see your creations and top rated examples sign into our main site https://midjourney.com/
- Need help? Ask your friends! Or go to our central server and click #trial-support
- Other useful commands /info for account details /settings for settings and /help for an overview
====
