== Prompts to sort

* Ironman taking a selfie with a GoPro while floating in the clouds in the sky, a selfie, one hand outreached holding the camera, fish eye lens, high detail, ultra realistic, cinematic lighting, portrait painting, photorealistic, Color Grading, portrait Photography, hyper - detailed, beautifully color graded, Unreal Engine5, Cinematic, --v 5 --s 750 --ar 3:2
* A magazine cover photo of a supermodel, photographed on a Leica S3 medium format camera. Wes Anderson inspired color grading. God rays. Backlit, sunset dappled lighting. Ethereal. Photographed for ELLE magazine. trending on 500px. --no text --ar 4:5 --s 750
* <https://s.mj.run/vlYVuPDTPek> <https://s.mj.run/WUN1v6dIXiM> a stunning woman, holding a book on fire to her chest, her hair is embellished with shimmering gold chains and delicate ornaments, hyper detailed, cinematic lighting, Kodak Vision3 500T film stock, 35 mm shot, diminished minimalism background, 8K resolution
* a sunlight comes through the forest with some trees, in the style of anime art, lush and detailed, storybook-like, anime-inspired, i can't believe how beautiful this is
* Doctor Strange taking a selfie with a GoPro on top of a building on Chinese palace , fish eye lens, high detail, ultra realistic, cinematic lighting, portrait painting, photorealistic, Color Grading, portrait Photography, hyper - detailed, beautifully color graded, Unreal Engine5, Cinematic 8K
* A surreal image of a giant jellyfish floating in the sky with its tentacles trailing down to the ground and wrapping around a city skyline.
* young female Obi Wan Kenobi, dynamic pose, in the style of Star Wars, yanjun cheng, krenz cushart, Frank Frazetta, ultra detailed illustration, tristan eaton, becky cloonan, serge marshennikov, spare and elegant brushwork, bone, eye-catching
* Wonder woman posing, portraiture, intense close - ups, Lois Van Baarle, by Krenz Cushart, Syd Mead, in the style of gold blue and red blink - and - you - miss - it detail, mirrored realms, suspended/ hanging, romanticized femininity
* Impasto oil watercolor and alcohol painting :: graceful beautiful gorgeous woman ballerina, Pino Daeni :: 3d arctic blue smoke and glacial blue swirling fog on white background :: romantic impressionism :: white background ::
* concept artist, Paul Chadeisson, futuristic cityscape, towering skyscrapers, advanced technology, bustling population, humans, robots, digital painting techniques, character, architecture, infrastructure, intricate details.
* Modern surreal extreme close up, Macro photo of pin up in heaven, beautiful eyes, dynamic pose, tilt angle by boris vallejo,Norman Rockwell, Milo manara, artgerm, mcbess UHD, 8k super Sharp Focus
* moon art, in the style of dreamlike illustrations, dark aquamarine and gold, colorful costumes, dreamy atmosphere, dark aquamarine and orange, celebrity portraits, dream-like atmosphere
* a woman’s head surrounded by multiple ovals and circles, in the style of richly detailed art nouveau, artgerm, sky-blue and amber, detailed world-building, orange and black, contrasting shadows, concert poster, alexandr averin
* https://twitter.com/mayorkingai/status/1652268384044589058?s=66&t=U90L9708TveKgva-sK5qYw 
** Light watercolor, blonde stunning girl walking at the beach, femenine, sunny day, watercolor painting, high details --ar 16:9 --v 5
** watercolor, medium portrait of a Geisha on sakura forest , red kimono , femenine, delicate , sunny day, watercolor painting, watercolor painting, various brushes, high details --ar 16:9
** Watercolor painting of a magical good morning, feature a hiker on top of a mountain, high quality watercolor painting, paint splashes, various brushes, warm colors --ar 16:9 --v 5
** Watercolor painting of a landscape of huangshan mountains in china, high quality watercolor, soft colors, various brushes, high quality --ar 16:9 --v 5
* https://twitter.com/g0rillaai/status/1651753153719615488?s=66&t=U90L9708TveKgva-sK5qYw
** a comic drawing of a [OBJECT] in front of [BUILDING], ivy plants and flowers, [TYPE] landscape, saturated plain colors, american scene matte painting, matte drawing, detailed, by artgerm and skottie young --ar 3:2 --niji 5 --style scenic
* https://twitter.com/iamneubert/status/1651624283985047552?s=66&t=U90L9708TveKgva-sK5qYw
** High [TOPIC] symmetrical close-up portrait shoot in [COLOR+LOCATION] of an [SUBJECT], anamorphic lens, ultra realistic, hyper detailed, [COLOR]-core, [LOCATION/STYLE]-core --ar 16:9 --v 5
*** [TOPIC]: fashion, automotive, biological
*** [COLOR+LOCATION]: green jungle, red volcano
*** [SUBJECT]: expressive supermodel wearing minimalistic green clothes
*** [COLOR]: Green-Core, Raspberry-Pink-Core
*** [LOCATION/STYLE]: Jungle-Core, Bubblegum-Core
** High automotive symmetrical close-up portrait shoot of a green mercedes-amg GT standing in the jungle, anamorphic lens, ultra realistic, hyper detailed, green-core, automotive-core --ar 16:9 --q 2 --v 5
* https://twitter.com/followmarcos/status/1650440146469134339?s=66&t=U90L9708TveKgva-sK5qYw
** cute SUBJECT's head emotions emoji sheet, for Twitch --niji 5

== Ideas

* Kids Coloring Book
* Twitter Campaign on Patriotic Cyber/IT Pics

== User Guide

* https://docs.midjourney.com/docs/quick-start

== General Prompt Links

* https://twitter.com/javilopen/status/1642934866726768641?s=66&t=U90L9708TveKgva-sK5qYw
* https://www.creativindie.com/best-midjourney-prompts-an-epic-list-of-crazy-text-to-image-ideas/#:~:text=Best%20MidJourney%20Prompts%3A%20camera%20lenses%20and%20filters&text=%E2%80%9CExpansive%20landscapes%2C%E2%80%9D%20%E2%80%9CSweeping,Including%20more%20of%20the%20scene.%E2%80%9D
* https://wgmimedia.com/how-to-make-a-logo-with-midjourney/
* https://www.ebaqdesign.com/blog/midjourney-logo-design
* https://www.midjourney.com/account/
* https://twitter.com/jhaddix/status/1645515555258990601?s=66&t=U90L9708TveKgva-sK5qYw
** IMAGE_TYPE: X | GENRE: X | EMOTION: X| SCENE: X | ACTORS: X | LOCATION TYPE: X | CAMERA MODEL: X | CAMERA LENSE: X | SPECIAL EFFECTS: X | TAGS: X, X, X, X, X — ar 16:9
* https://medium.com/@neonforge/chatgpt-midjourney-dall-e-and-stable-diffusion-how-to-create-amazing-images-for-almost-any-5daced80f376

== Signup

====
Midjourney Bot
 — Today at 9:26 AM
Heya @chrismh, we're excited to have you as part of the Midjourney Beta!

Other important tips
- For visual guides and docs  https://docs.midjourney.com/docs/quick-start
- When your trial ends type /subscribe or go to https://midjourney.com/account
- To see your creations and top rated examples sign into our main site https://midjourney.com/
- Need help? Ask your friends! Or go to our central server and click #trial-support
- Other useful commands /info for account details /settings for settings and /help for an overview
====
